# OCR Project

OCAML=ocamlopt
OCAMLFLAGS = -I +lablgtk2
OCAMLLD = lablgtk.cmxa
FILES = interface.ml
SORTIE = -o interface

tpsdl:
	${OCAML} ${OCAMLFLAGS} ${OCAMLLD} ${SORTIE} ${FILES}


clean:: 
	rm -f *~ *.o *.cm? interface

# End



